debug = false
timezone = "Europe/Paris"

# Your cron jobs
# Might not be a good idea to modify if you're not sure what you're doing
[[schedule]]
name = "daytime"
cron = "* 6-21 * * 1-5" # every minute at daytime during the week

[[schedule]]
name = "night"
cron = "*/5 1,2,3,4,5,22,23 * * 1-5" # every 5 minutes at night during the week

[[schedule]]
name = "weekend"
cron = "*/5 * * * 6,7" # every 5 minutes during weekends

# Discord servers
[[servers]]
name = "example server"
webhook = "https://discord.com/api/webhooks/REPLACE/MEPLEASE"
# Use valid site template name (list in discord.ts) + post channel id /!\ must be a string
DOFUS_RETRO = "6969696969696969"
WAVEN = "6969696969696969"
DOFUS = "6969696969696969"
# others is special chan for anything that doesn't match others templates (can also be the only chan)
others = "6969696969696969"

# You can add as many servers as you want
[[servers]]
name = "example 2"
webhook = "https://discord.com/api/webhooks/REPLACE/MEPLEASE"
DOFUS_RETRO = "6969696969696969"
others = "6969696969696969"
