services:
  dragoturkey:
    image: ghcr.io/daweyy/dragoturkey:main
    restart: unless-stopped
    container_name: dragoturkey
    volumes:
      - ./config.toml:/app/config.toml
      - ./data.json:/app/data.json