services:
  dragoturkey:
    image: oven/bun:latest
    command: bun install && bun run start
    restart: unless-stopped
    container_name: dragoturkey
    working_dir: /app
    volumes:
      - .:/app