services:
  dragoturkey:
    image: ghcr.io/daweyy/dragoturkey:main
    restart: unless-stopped
    container_name: dragoturkey
    volumes:
      - ./.env:/app/.env
      - ./data.json:/app/data.json